name: deploy

on:
  push:
    branches: [main]

jobs:
  static_site:

    # Do not attempt to deploy on forks
    if: github.repository_owner == 'BIDS-numpy'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip list

    - name: Build docs
      if: github.ref == 'refs/heads/main'
      run: make -C site/ html

    # Deploy to github pages, nothing fancy
    - name: Deploy docs
      if: github.ref == 'refs/heads/main'
      run: ghp-import -n -f -p site/build/html
